/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package vista;

import controlador.GestionDepartamento;
import javax.swing.JOptionPane;
import modelo.Departamento;

/**
 *
 * @author Usuario
 */
public class Ejercico6 extends javax.swing.JFrame {

    /**
     * Creates new form Ejercico6
     */
    public Ejercico6() {
        initComponents();
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        jTextArea1 = new javax.swing.JTextArea();
        jPasswordField1 = new javax.swing.JPasswordField();
        lfNombreDeperatemnto = new javax.swing.JLabel();
        tfNumeroDepartamento = new javax.swing.JTextField();
        lfNumero1 = new javax.swing.JLabel();
        tfNNombre = new javax.swing.JTextField();
        lfLoacalidad = new javax.swing.JLabel();
        tfLocalidad = new javax.swing.JTextField();

        jTextArea1.setColumns(20);
        jTextArea1.setRows(5);
        jScrollPane1.setViewportView(jTextArea1);

        jPasswordField1.setText("jPasswordField1");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        lfNombreDeperatemnto.setText("Nombre");

        tfNumeroDepartamento.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                tfNumeroDepartamentoFocusLost(evt);
            }
        });
        tfNumeroDepartamento.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tfNumeroDepartamentoActionPerformed(evt);
            }
        });

        lfNumero1.setText("Número");

        tfNNombre.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tfNNombreActionPerformed(evt);
            }
        });

        lfLoacalidad.setText("Localizad");

        tfLocalidad.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tfLocalidadActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(29, 29, 29)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                        .addComponent(lfLoacalidad)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(tfLocalidad, javax.swing.GroupLayout.DEFAULT_SIZE, 245, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                        .addComponent(lfNombreDeperatemnto)
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(tfNumeroDepartamento, javax.swing.GroupLayout.DEFAULT_SIZE, 247, Short.MAX_VALUE)
                            .addComponent(tfNNombre))))
                .addContainerGap(244, Short.MAX_VALUE))
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addGap(32, 32, 32)
                    .addComponent(lfNumero1)
                    .addContainerGap(507, Short.MAX_VALUE)))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(39, 39, 39)
                .addComponent(tfNumeroDepartamento, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(28, 28, 28)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lfNombreDeperatemnto)
                    .addComponent(tfNNombre, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(28, 28, 28)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lfLoacalidad)
                    .addComponent(tfLocalidad, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(282, Short.MAX_VALUE))
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addGap(39, 39, 39)
                    .addComponent(lfNumero1)
                    .addContainerGap(404, Short.MAX_VALUE)))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void tfNumeroDepartamentoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tfNumeroDepartamentoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tfNumeroDepartamentoActionPerformed

    private void tfNNombreActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tfNNombreActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tfNNombreActionPerformed

    private void tfLocalidadActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tfLocalidadActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tfLocalidadActionPerformed

    private void tfNumeroDepartamentoFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_tfNumeroDepartamentoFocusLost
        comprobarDepartamento();
    }//GEN-LAST:event_tfNumeroDepartamentoFocusLost

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Ejercico6.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Ejercico6.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Ejercico6.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Ejercico6.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Ejercico6().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPasswordField jPasswordField1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextArea jTextArea1;
    private javax.swing.JLabel lfLoacalidad;
    private javax.swing.JLabel lfNombreDeperatemnto;
    private javax.swing.JLabel lfNumero1;
    private javax.swing.JTextField tfLocalidad;
    private javax.swing.JTextField tfNNombre;
    private javax.swing.JTextField tfNumeroDepartamento;
    // End of variables declaration//GEN-END:variables

public void comprobarDepartamento(){
     String txt= tfNumeroDepartamento.getText();
     txt=txt.trim();
     int n;
    
       if(txt.isEmpty()){
         JOptionPane.showMessageDialog(null, "Debe introducir el valor de departamento");
        }else{
     try{
     n=Integer.parseInt(txt);
      
       if(GestionDepartamento.isDepartament(n)){
         Departamento d=GestionDepartamento.obtenerDepartamentoPorID(n);
         tfNNombre.setText(d.getNombreDepartamento());
         tfLocalidad.setText(d.getLocalizacionDepargamento());
        }else{
           JOptionPane.showMessageDialog(null, "no es un departamento válido");
       }
     }catch(NumberFormatException e){
         JOptionPane.showMessageDialog(null,"Error de formato debe ser un número");
     
     }
       }
            
     }
     

}
